Repository CEOS-PAT-PLATE/BackEnd, pull requests merged in 2024-07, with the labels that each got.

#45 Feat/#44 pet profile image
  src/main/java/com/petplate/petplate/pet/controller/PetController.java
  src/main/java/com/petplate/petplate/pet/domain/ProfileImg.java
  src/main/java/com/petplate/petplate/pet/dto/request/ModifyPetProfileImgRequestDto.java
  src/main/java/com/petplate/petplate/pet/dto/response/ReadPetProfileImageResponseDto.java
  src/main/java/com/petplate/petplate/pet/service/PetService.java
  src/test/java/com/petplate/petplate/pet/service/PetServiceTest.java
Labels: feature, refactoring, test

#48 Feat : 영양제 리스트 전체 조회, 영양제 삭제
  src/main/java/com/petplate/petplate/drug/controller/DrugCRUDController.java
  src/main/java/com/petplate/petplate/drug/controller/DrugRecommendController.java
  src/main/java/com/petplate/petplate/drug/domain/entity/Drug.java
  src/main/java/com/petplate/petplate/drug/dto/response/DrugResponseDto.java
  src/main/java/com/petplate/petplate/drug/dto/response/RecommendDrugResponseDto.java
  src/main/java/com/petplate/petplate/drug/repository/DrugNutrientRepository.java
  src/main/java/com/petplate/petplate/drug/service/DrugCRUDService.java
  src/main/java/com/petplate/petplate/drug/service/DrugRecommendService.java
  src/test/java/com/petplate/petplate/drug/controller/DrugCRUDControllerTest.java
  src/test/java/com/petplate/petplate/drug/controller/DrugRecommendControllerTest.java
  src/test/java/com/petplate/petplate/drug/repository/DrugNutrientRepositoryTest.java
  src/test/java/com/petplate/petplate/drug/repository/DrugRepositoryTest.java
  src/test/java/com/petplate/petplate/drug/service/DrugCRUDServiceTest.java
  src/test/java/com/petplate/petplate/drug/service/DrugRecommendServiceTest.java
Labels: feature, refactoring, test

#50 Refactor: 휴대폰 전화 번호 안받는 것으로 수정 (#49)
  src/main/java/com/petplate/petplate/auth/oauth/OAuthAttributes.java
  src/main/java/com/petplate/petplate/auth/oauth/userinfo/NaverOAuth2UserInfo.java
  src/main/java/com/petplate/petplate/auth/oauth/userinfo/OAuth2UserInfo.java
  src/main/java/com/petplate/petplate/user/domain/entity/User.java
Labels: refactoring

#54 Refactor/#53 drug controller
  src/main/java/com/petplate/petplate/drug/controller/DrugRecommendController.java
  src/main/java/com/petplate/petplate/drug/service/DrugRecommendService.java
  src/test/java/com/petplate/petplate/drug/controller/DrugRecommendControllerTest.java
  src/test/java/com/petplate/petplate/drug/service/DrugRecommendServiceTest.java
Labels: feature, refactoring

#56 Refactor/#52 social login 1
  src/main/java/com/petplate/petplate/auth/oauth/cookie/HttpCookieOAuth2AuthorizationRequestRepository.java
  src/main/java/com/petplate/petplate/auth/oauth/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/petplate/petplate/auth/oauth/service/CustomOAuth2UserService.java
  src/main/java/com/petplate/petplate/common/config/SecurityConfig.java
  src/main/java/com/petplate/petplate/common/utils/CookieUtils.java
Labels: feature

#61 Feat/#60 show my profile
  src/main/java/com/petplate/petplate/auth/fortest/SocialLoginAndJwtTestController.java
  src/main/java/com/petplate/petplate/drug/controller/DrugCRUDController.java
  src/main/java/com/petplate/petplate/drug/controller/DrugRecommendController.java
  src/main/java/com/petplate/petplate/user/controller/UserController.java
  src/main/java/com/petplate/petplate/user/controller/UserSignUpController.java
  src/main/java/com/petplate/petplate/user/dto/response/MyProfileResponseDto.java
  src/main/java/com/petplate/petplate/user/service/UserService.java
Labels: feature, refactoring

#64 Feat/#62 로그아웃, 회원탈퇴 ,토큰 재발급
  build.gradle
  src/main/java/com/petplate/petplate/auth/controller/AuthController.java
  src/main/java/com/petplate/petplate/auth/dto/response/TokenReIssueResponseDto.java
  src/main/java/com/petplate/petplate/auth/oauth/Dto/SocialLoginReIssueResponseDto.java
  src/main/java/com/petplate/petplate/auth/oauth/OAuthAttributes.java
  src/main/java/com/petplate/petplate/auth/oauth/service/CustomOAuth2LoginAuthenticationProvider.java
  src/main/java/com/petplate/petplate/auth/oauth/service/CustomOAuth2UserService.java
  src/main/java/com/petplate/petplate/auth/oauth/service/SocialLoginTokenUtil.java
  src/main/java/com/petplate/petplate/auth/service/AuthService.java
  src/main/java/com/petplate/petplate/common/config/SecurityConfig.java
  src/main/java/com/petplate/petplate/common/config/WebClientConfig.java
  src/main/java/com/petplate/petplate/common/response/error/ErrorCode.java
  src/main/java/com/petplate/petplate/user/controller/UserController.java
  src/main/java/com/petplate/petplate/user/domain/entity/User.java
  src/main/java/com/petplate/petplate/user/service/UserService.java
Labels: feature

#75 Refactoring/#74 changeget deficient nutrient on recommend drug
  src/main/java/com/petplate/petplate/drug/controller/DrugRecommendController.java
  src/main/java/com/petplate/petplate/drug/service/DrugRecommendService.java
  src/test/java/com/petplate/petplate/drug/controller/DrugCRUDControllerTest.java
  src/test/java/com/petplate/petplate/drug/controller/DrugRecommendControllerTest.java
  src/test/java/com/petplate/petplate/drug/service/DrugRecommendServiceTest.java
Labels: refactoring

#77 Refactor/#76 set api auth
  src/main/java/com/petplate/petplate/auth/jwt/handler/JwtAccessDeniedHandler.java
  src/main/java/com/petplate/petplate/common/config/SecurityConfig.java
  src/main/java/com/petplate/petplate/user/controller/UserController.java
  src/main/java/com/petplate/petplate/user/domain/entity/User.java
  src/main/java/com/petplate/petplate/user/dto/request/SecretCodeRequestDto.java
  src/main/java/com/petplate/petplate/user/service/UserService.java
Labels: feature, refactoring

#83 Refactor: JWT 코드 상 기간 원상 복구
  src/main/java/com/petplate/petplate/auth/jwt/TokenProvider.java
Labels: refactoring

#94 Refactor :redirect url 임시 설정 (#93)
  src/main/java/com/petplate/petplate/auth/oauth/handler/OAuth2LoginSuccessHandler.java
Labels: refactoring

#95 Refactor: Redirect URL 수정 (#93)
  src/main/java/com/petplate/petplate/auth/oauth/handler/OAuth2LoginSuccessHandler.java
Labels: refactoring

#107 Feat/#106 login by code
  src/main/java/com/petplate/petplate/auth/controller/AuthController.java
  src/main/java/com/petplate/petplate/auth/dto/response/AuthResponseWithTokenAndRedirectUserInfo.java
  src/main/java/com/petplate/petplate/auth/dto/response/UserEnrollResponseDto.java
  src/main/java/com/petplate/petplate/auth/jwt/TokenProvider.java
  src/main/java/com/petplate/petplate/auth/oauth/Dto/NaverResponse.java
  src/main/java/com/petplate/petplate/auth/oauth/Dto/SocialLoginCheckDeleteResponseDto.java
  src/main/java/com/petplate/petplate/auth/oauth/Dto/SocialLoginCheckValidateAccessToken.java
  src/main/java/com/petplate/petplate/auth/oauth/Dto/SocialLoginProfileResponseDto.java
  src/main/java/com/petplate/petplate/auth/oauth/Dto/SocialLoginTokenRequestResponseDto.java
  src/main/java/com/petplate/petplate/auth/oauth/service/CustomOAuth2LoginAuthenticationProvider.java
  src/main/java/com/petplate/petplate/auth/oauth/service/SocialLoginTokenUtil.java
  src/main/java/com/petplate/petplate/auth/service/AuthService.java
  src/main/java/com/petplate/petplate/common/config/SecurityConfig.java
  src/main/java/com/petplate/petplate/common/response/error/ErrorCode.java
  src/main/java/com/petplate/petplate/user/controller/UserController.java
Labels: bug, feature

#109 Feat: refreshTOken redis 저장
  src/main/java/com/petplate/petplate/auth/service/AuthService.java
Labels: refactoring

#110 Refactor: login success url with pet enroll (#108)
  src/main/java/com/petplate/petplate/auth/oauth/handler/OAuth2LoginSuccessHandler.java
Labels: feature

#118 Refactor/#117 drugrecommend dto
  src/main/java/com/petplate/petplate/drug/controller/DrugRecommendController.java
  src/main/java/com/petplate/petplate/drug/dto/response/RecommendDrugResponseDtoWithNutrientName.java
  src/main/java/com/petplate/petplate/drug/repository/DrugRepository.java
  src/main/java/com/petplate/petplate/drug/service/DrugRecommendService.java
  src/test/java/com/petplate/petplate/drug/controller/DrugRecommendControllerTest.java
  src/test/java/com/petplate/petplate/drug/service/DrugRecommendServiceTest.java
Labels: refactoring

#122 Bug/#121 social unlink
  src/main/java/com/petplate/petplate/auth/oauth/Dto/SocialInfoWithTokenDto.java
  src/main/java/com/petplate/petplate/auth/oauth/Dto/SocialLoginProfileResponseDto.java
  src/main/java/com/petplate/petplate/auth/oauth/service/CustomOAuth2UserService.java
  src/main/java/com/petplate/petplate/auth/oauth/service/SocialLoginTokenUtil.java
  src/main/java/com/petplate/petplate/auth/service/AuthService.java
Labels: bug

#133 Feat/#132 prod server cicd
  .github/workflows/cicd-prod.yml
  .gitignore
Labels: feature

#138 Refactor: api/v1/raws 경로 로그인 없이로 수정 (#137)
  src/main/java/com/petplate/petplate/common/config/SecurityConfig.java
Labels: refactoring

#147 Refactor/#146 nutrient for disease
  src/main/java/com/petplate/petplate/common/response/error/ErrorCode.java
  src/main/java/com/petplate/petplate/drug/controller/DrugUsefulPartController.java
  src/main/java/com/petplate/petplate/drug/domain/entity/Drug.java
  src/main/java/com/petplate/petplate/drug/domain/entity/DrugDrugUsefulPart.java
  src/main/java/com/petplate/petplate/drug/domain/entity/DrugUsefulPart.java
  src/main/java/com/petplate/petplate/drug/dto/request/DrugSaveRequestDto.java
  src/main/java/com/petplate/petplate/drug/dto/request/DrugUsefulPartSaveRequestDto.java
  src/main/java/com/petplate/petplate/drug/dto/response/DrugResponseDto.java
  src/main/java/com/petplate/petplate/drug/dto/response/DrugUsefulPartResponseDto.java
  src/main/java/com/petplate/petplate/drug/repository/DrugDrugUsefulPartRepository.java
  src/main/java/com/petplate/petplate/drug/repository/DrugRepository.java
  src/main/java/com/petplate/petplate/drug/repository/DrugUsefulPartRepository.java
  src/main/java/com/petplate/petplate/drug/service/DrugCRUDService.java
  src/main/java/com/petplate/petplate/drug/service/DrugRecommendService.java
  src/main/java/com/petplate/petplate/drug/service/DrugUsefulPartService.java
  src/test/java/com/petplate/petplate/drug/controller/DrugCRUDControllerTest.java
  src/test/java/com/petplate/petplate/drug/repository/DrugDrugUsefulPartRepositoryTest.java
  src/test/java/com/petplate/petplate/drug/service/DrugCRUDServiceTest.java
  src/test/java/com/petplate/petplate/drug/service/DrugRecommendServiceTest.java
Labels: feature, refactoring

#148 Refactor: cicd yml dev 명시
  .github/workflows/cicd-dev.yml
Labels: refactoring

#149 [Feat] production 반영
  .github/workflows/cicd-dev.yml
  src/main/java/com/petplate/petplate/common/config/SecurityConfig.java
  src/main/java/com/petplate/petplate/common/response/error/ErrorCode.java
  src/main/java/com/petplate/petplate/dailyMealNutrient/repository/ProperNutrientRepository.java
  src/main/java/com/petplate/petplate/dailyMealNutrient/repository/SufficientNutrientRepository.java
  src/main/java/com/petplate/petplate/dailyMealNutrient/service/DeficientNutrientService.java
  src/main/java/com/petplate/petplate/dailyMealNutrient/service/ProperNutrientService.java
  src/main/java/com/petplate/petplate/dailyMealNutrient/service/SufficientNutrientService.java
  src/main/java/com/petplate/petplate/drug/controller/DrugRecommendController.java
  src/main/java/com/petplate/petplate/drug/controller/DrugUsefulPartController.java
  src/main/java/com/petplate/petplate/drug/domain/entity/Drug.java
  src/main/java/com/petplate/petplate/drug/domain/entity/DrugDrugUsefulPart.java
  src/main/java/com/petplate/petplate/drug/domain/entity/DrugUsefulPart.java
  src/main/java/com/petplate/petplate/drug/dto/request/DrugSaveRequestDto.java
  src/main/java/com/petplate/petplate/drug/dto/request/DrugUsefulPartSaveRequestDto.java
  src/main/java/com/petplate/petplate/drug/dto/response/DrugResponseDto.java
  src/main/java/com/petplate/petplate/drug/dto/response/DrugUsefulPartResponseDto.java
  src/main/java/com/petplate/petplate/drug/repository/DrugDrugUsefulPartRepository.java
  src/main/java/com/petplate/petplate/drug/repository/DrugRepository.java
  src/main/java/com/petplate/petplate/drug/repository/DrugUsefulPartRepository.java
  src/main/java/com/petplate/petplate/drug/service/DrugCRUDService.java
  src/main/java/com/petplate/petplate/drug/service/DrugRecommendService.java
  src/main/java/com/petplate/petplate/drug/service/DrugUsefulPartService.java
  src/main/java/com/petplate/petplate/pet/service/PetService.java
  src/main/java/com/petplate/petplate/petdailymeal/controller/DailyMealController.java
  src/main/java/com/petplate/petplate/utils/DailyMealUtil.java
  src/test/java/com/petplate/petplate/drug/controller/DrugCRUDControllerTest.java
  src/test/java/com/petplate/petplate/drug/repository/DrugDrugUsefulPartRepositoryTest.java
  src/test/java/com/petplate/petplate/drug/service/DrugCRUDServiceTest.java
  src/test/java/com/petplate/petplate/drug/service/DrugRecommendServiceTest.java
Labels: feature

#152 [Refactor] DrugUsefulPart 인가 처리
  src/main/java/com/petplate/petplate/common/config/SecurityConfig.java
Labels: refactoring
